name: CI BarberBook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend Angular
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências do frontend
        run: npm install

      - name: Build do frontend
        run: npm run build

  backend:
    name: Backend NestJS
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: test-secret
      GOOGLE_CLIENT_ID: test-client-id
      GOOGLE_CLIENT_SECRET: test-client-secret
      GOOGLE_CALLBACK_URL: http://localhost:3000/api/auth/google/callback
      FRONTEND_URL: http://localhost:4200
      NODE_ENV: test

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências do backend
        run: npm install --include=dev

      - name: Gerar Prisma Client
        run: npx prisma generate

      - name: Build do backend
        run: npm run build